adsenename: Jekyll site CIhttps://github.com/Shabbabogleroses/shabbaboglegethub.com
on:
  push:
    branches: [ "main" ]https://github.com/Shabbabogleroses/shabbaboglegethub.com  pull_request:
    branches: [ "main" ]https://github.com/Shabbabogleroses/shabbaboglegethub.com
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
